client/src/components/Card.jsx, package-lock.json
Improved the recommendation component and added space between text and video.
=> added space between text and video

client/src/pages/Home.jsx
=> added spinner

client/src/pages/SignIn.jsx, client/src/utils/spinner.jsx
=> centered loading spinner

CODE_OF_CONDUCT.md, CONTRIBUTING.md
#10 
Improves Documentation of the project , please provide a valuable feedback to edit the content
#example
=> Improved Documentation

client/src/pages/Home.jsx
Issue(#4)
I have solved the issue that is to reduce the distance in between cards in home page
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
Added a screenshot.
=> freshcommit

client/src/components/Card.jsx
#7 
https://user-images.githubusercontent.com/99071072/219499023-1eedf4fc-f27a-481e-8a89-d8aa0152fee4.mp4
=> added hover effects

LICENSE, README.md
#example
- Added LICENSE
- Changes README.md
- Resolved issue #13 
=> Fully changed and beautified README.md 

client/src/pages/SignIn.jsx, client/src/utils/errorMessage.jsx
#26 
#example
https://user-images.githubusercontent.com/92199877/219654846-9351c8b9-cb2f-4185-a57b-6516ff282382.mp4
=> added cross icon in error of signin page

client/src/App.js, client/src/utils/useNetworkStatus.js
#31 
#example
https://user-images.githubusercontent.com/92199877/219864364-27c7b939-56d6-4551-a45a-4e8f08fcab96.mp4
=> message shown if user is offline

client/src/pages/Search.jsx, client/src/utils/spinsearch.jsx, client/src/utils/spinsearch2.css
mecivil
Contributor
Fixes Issue
https://github.com/mnnkhndlwl/mern_youtube_clone/issues/28
#example
- [ x] My code follows the code style of this project.
- [x ] All new and existing tests passed.
https://user-images.githubusercontent.com/98341366/219866328-0b7718c5-b138-42c9-acc4-da4df29e985d.mp4
Added a screenshot of the changed output.
=> Centred the spinner

client/src/components/Navbar.jsx
=> added effects in search and made like real youtube

client/src/components/Navbar.jsx
fixes - #40 
#example
Added Z-index in Navbar
=> [Update]: Added Z-index in Navbar

client/public/index.html
new custom scroll bar for youtube clone
fixes - #5
#example
Added custom scrollbar
- [ X] My code follows the code style of this project.
- [X ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.
=> #5 issue- Create a custom scrollbar

client/src/index.css
This PR fixes the following issues: #43 
#example
=> [Bug fix] Fixed bottom scrollbar bug

client/src/pages/Video.jsx
Issue number : #27 
If the user is not signed in and if he is trying to subscribe to a channel, then an alert message will pop that will tell him to sign in first and then try to subscribe again.
https://user-images.githubusercontent.com/99071072/221360428-fafa35aa-896d-48e5-b4cc-7a928086149a.mp4
=> alert message pops if user is not signed in and trying to subscribe

client/package-lock.json, client/package.json, client/src/index.js, client/src/pages/Video.jsx
1. Hover Effect on Share button
2. Copy video link in clipboard
3. Show a success snackbar
=> Fixes #52 [`Share Button`]

client/src/App.js, client/src/components/Menu.jsx, client/src/components/Navbar.jsx, client/src/pages/Home.jsx
This PR fixes the following issues: fixes #47 
#example
Sidebar menu responsive 
make a toggle button which use to open and close sidebar
Add all the screenshots and a video which support your changes 
Open Sidebar
Close Sidebar
=> [UPDATE] : Sidebar Responsive

client/src/App.js, client/src/components/Navbar.jsx, client/src/index.js, client/src/pages/Home.jsx, client/src/pages/Profile.jsx, client/src/pages/SignIn.jsx
=> Closes #50 [`Search Bar`]

client/src/components/Comment.jsx, client/src/pages/Video.jsx, server/controllers/comment.js, server/controllers/video.js, server/models/User.js
Creating a Super User can be done by adding a `'isSuperUser': true`, in the request body while sending it to `/signup` [POST]
A SuperUser can delete any comment or video.
**Dummy SuperUser:** 
Username: `Manan`
Password: `admin123!`
Username: `Super Tanmay`
Password: `admin123!` 
This PR fixes the following issues: #37 
=> Closes #37 `Feature/SuperUser`

client/src/App.js, client/src/components/Card.jsx, client/src/components/Comments.jsx, client/src/components/Navbar.jsx, client/src/pages/Home.jsx, client/src/pages/Video.jsx
#64 
I have add css to homepage and videopage inorder to make it mobile reponsiveness
=> Mobile Responsive

client/src/components/Card.jsx, client/src/pages/Video.jsx
This PR fixes the following issues: #65 
#example
https://user-images.githubusercontent.com/95460021/224230501-3a191db3-4bea-47c3-87a6-5c631d9893f9.mp4
https://user-images.githubusercontent.com/95460021/224232100-f7fbb5f3-9609-423a-99e4-ca4df2325cac.mp4
=> Added loading spinner in video

client/src/App.js, client/src/components/Menu.jsx, client/src/components/ReportModal.jsx, client/src/config.js, server/controllers/report.js, server/index.js, server/models/Report.js, server/routes/reports.js
**New Routes :**
Get All Reported Issues: `/api/reports/` [GET]
Report New Issue: `/api/reports/new` [POST] 
```js
Required Body
{userId: String, issue: String}
```
#38 
https://user-images.githubusercontent.com/84321236/224471041-6ca6685e-6068-4b7c-806f-1a3c14a62a8e.mp4
=> Fixes #38 Feature/issue reporting

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Navbar.jsx
Mic glows when activated.
This PR fixes the following issues: #74 
Add all the screenshots and a video which support your changes 
https://user-images.githubusercontent.com/84321236/224505669-32368f54-17d1-4b3a-b633-4118833657d5.mp4
=> Closes #74 `Feature/VoiceSearch`

client/src/pages/Video.jsx
#75 
I have add css to redesign the like , dislike, share and save button
=>  Changes is made in video component

client/package-lock.json, client/package.json, client/src/utils/useNetworkStatus.js
#77
#example
https://user-images.githubusercontent.com/92199877/225213983-edcc2ea6-a0d7-437a-8812-567ee59905fa.mp4
=> online status shown using isOnline library

README.md
This PR fixes the following issues: #83 
#example
=> Add Hacktoberfest Logo to Docs
